_wandb:
    value:
        cli_version: 0.23.1
        e:
            cugin1fxd76g87yh31ih0g3wozjetkf3:
                args:
                    - --batch_size
                    - "32"
                    - --lr
                    - "0.1"
                    - --seed
                    - "42"
                    - --input_path
                    - C:/Users/kl23a/Documents/Working/FedCVD/code/FedCVD/scripts/ecg/../../../../data
                    - --output_path
                    - C:/Users/kl23a/Documents/Working/FedCVD/code/FedCVD/scripts/ecg/../../../../output
                    - --max_epoch
                    - "50"
                codePath: code\FedCVD\trainers\centralized_ecg.py
                codePathLocal: trainers\centralized_ecg.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1013310287872"
                        used: "222080913408"
                email: lekien140405@gmail.com
                executable: C:\Users\kl23a\.conda\envs\fedcvd_env\python.exe
                git:
                    commit: e7d1e03fff0dacdad22c51bc705a4591534748db
                    remote: https://github.com/SMILELab-FL/FedCVD.git
                gpu: NVIDIA GeForce RTX 5080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 10752
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5080
                      uuid: GPU-b62e4ca1-4ffc-4067-a225-c2ca2e69cd48
                host: CAPS-14QKMD4
                memory:
                    total: "68135153664"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\kl23a\Documents\Working\FedCVD\code\FedCVD\trainers\centralized_ecg.py
                python: CPython 3.12.12
                root: C:\Users\kl23a\Documents\Working\FedCVD\code\FedCVD
                startedAt: "2026-01-09T21:04:04.475822Z"
                writerId: cugin1fxd76g87yh31ih0g3wozjetkf3
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 48
                - 53
            "2":
                - 1
                - 5
                - 41
                - 48
                - 53
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.12
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
criterion:
    value: BCELoss
dataset:
    value: ECG
lr:
    value: 0.1
max_epoch:
    value: 50
model:
    value: resnet1d34
seed:
    value: 42
